### PR TITLE
Feature/server side pagination

### PR DESCRIPTION
**Pull request by cbankester**
* Added a test suite (Mocha+Karma+Chai+Sinon)
* Added server side pagination support
  * Construction of server-side pagination differs slightly from the initial proposal:
  ```javascript
  new DataTable({
    serverSidePagination: {
      enabled: true,
      path: '/foo/bar',
      loader: function(result){...}
    }
  });
  ```

### CODE REVIEW

**Comment by cmckni3** [comment]
Works pretty well. Does `loading` ever get set to true?

**Comment by cbankester** [comment]
Hm, no, I completely ignored `loading`. When should it be set to `true`/`false`? I assume just when the client is waiting on the server?

**Comment by cmckni3** [comment]
Yeah when waiting on the server. I saw it is set to `false` when it is finished but never set to `true`.

**Comment by cbankester** [comment]
Haha, mk, I'll get that in there. There are also a lot of things we can refactor in there now (a lot of public methods that don't need to be public, etc.), but I think we should do the refactoring on a `1.0.0` tag (removing public methods => not backward compatible).

**Comment by cmckni3** [comment]
Cool. That makes sense.

**Comment by cbankester** [comment]
Fixes #17, #24

**Pull request merged**
